#!/usr/bin/env python3
"""
build_hwpx.py - Assemble HWPX files from component XML files.

Combines section XML files (typically generated by Claude) with base template
files to produce a valid HWPX document that Hancom Office can open.

HWPX is a ZIP-based format (application/hwp+zip) with strict ordering and
compression requirements:
  - mimetype: first entry, STORED (uncompressed)
  - version.xml: STORED
  - XML files: DEFLATED
  - Image files (jpg, png, bmp, jpeg): STORED (already compressed)

Usage:
    python3 build_hwpx.py --section section0.xml --output output.hwpx
    python3 build_hwpx.py --section section0.xml --output out.hwpx \\
        --header custom_header.xml --title "문서 제목" --images img1.jpg img2.png

Python 3.9+ standard library only.
"""

import argparse
import os
import re
import shutil
import sys
import tempfile
import zipfile
from datetime import datetime


# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_TEMPLATE = os.path.normpath(os.path.join(SCRIPT_DIR, "..", "templates", "base"))

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp"}

# Media types for content.hpf manifest items
IMAGE_MEDIA_TYPES = {
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".png": "image/png",
    ".bmp": "image/bmp",
}


# ---------------------------------------------------------------------------
# content.hpf generation
# ---------------------------------------------------------------------------

def generate_content_hpf(template_path: str,
                         section_files: list[str],
                         image_files: list[str],
                         title: str,
                         date_str: str) -> str:
    """Read the template content.hpf and update it with actual sections,
    images, title, and date metadata.

    Rather than doing fragile XML parsing with the standard library on a
    namespace-heavy document, we do careful string manipulation that preserves
    the template's namespace declarations and structure.
    """
    hpf_path = os.path.join(template_path, "Contents", "content.hpf")
    with open(hpf_path, "r", encoding="utf-8") as f:
        content = f.read()

    # --- Update title ---
    content = re.sub(
        r"<opf:title[^/]*/?>.*?(?:</opf:title>)?",
        f"<opf:title>{_xml_escape(title)}</opf:title>",
        content,
        count=1,
        flags=re.DOTALL,
    )

    # --- Update date metadata ---
    content = re.sub(
        r'(<opf:meta\s+name="CreatedDate"\s+content=")[^"]*(")',
        rf"\g<1>{date_str}\2",
        content,
    )
    content = re.sub(
        r'(<opf:meta\s+name="ModifiedDate"\s+content=")[^"]*(")',
        rf"\g<1>{date_str}\2",
        content,
    )
    content = re.sub(
        r'(<opf:meta\s+name="date"\s+content=")[^"]*(")',
        rf"\g<1>{date_str}\2",
        content,
    )

    # --- Rebuild <opf:manifest> ---
    manifest_items = []
    manifest_items.append(
        '    <opf:item id="header" href="Contents/header.xml" media-type="application/xml"/>'
    )
    for sec in section_files:
        sec_id = os.path.splitext(sec)[0]  # e.g. "section0"
        manifest_items.append(
            f'    <opf:item id="{sec_id}" href="Contents/{sec}" media-type="application/xml"/>'
        )
    manifest_items.append(
        '    <opf:item id="settings" href="settings.xml" media-type="application/xml"/>'
    )
    for img in image_files:
        img_id = _make_id(img)
        ext = os.path.splitext(img)[1].lower()
        media = IMAGE_MEDIA_TYPES.get(ext, "application/octet-stream")
        manifest_items.append(
            f'    <opf:item id="{img_id}" href="BinData/{img}" media-type="{media}" isEmbeded="1"/>'
        )

    manifest_block = "  <opf:manifest>\n" + "\n".join(manifest_items) + "\n  </opf:manifest>"
    content = re.sub(
        r"[ \t]*<opf:manifest>.*?</opf:manifest>",
        manifest_block,
        content,
        count=1,
        flags=re.DOTALL,
    )

    # --- Rebuild <opf:spine> ---
    spine_items = []
    spine_items.append('    <opf:itemref idref="header" linear="yes"/>')
    for sec in section_files:
        sec_id = os.path.splitext(sec)[0]
        spine_items.append(f'    <opf:itemref idref="{sec_id}" linear="yes"/>')

    spine_block = "  <opf:spine>\n" + "\n".join(spine_items) + "\n  </opf:spine>"
    content = re.sub(
        r"[ \t]*<opf:spine>.*?</opf:spine>",
        spine_block,
        content,
        count=1,
        flags=re.DOTALL,
    )

    return content


# ---------------------------------------------------------------------------
# container.rdf generation
# ---------------------------------------------------------------------------

def generate_container_rdf(section_files: list[str]) -> str:
    """Generate META-INF/container.rdf with entries for the header and all
    section files."""
    lines = [
        '<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>',
        '<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">',
    ]

    # Header entry
    lines.append('  <rdf:Description rdf:about="">')
    lines.append(
        '    <ns0:hasPart xmlns:ns0="http://www.hancom.co.kr/hwpml/2016/meta/pkg#"'
        ' rdf:resource="Contents/header.xml"/>'
    )
    lines.append("  </rdf:Description>")
    lines.append('  <rdf:Description rdf:about="Contents/header.xml">')
    lines.append(
        '    <rdf:type rdf:resource="http://www.hancom.co.kr/hwpml/2016/meta/pkg#HeaderFile"/>'
    )
    lines.append("  </rdf:Description>")

    # Section entries
    for sec in section_files:
        lines.append('  <rdf:Description rdf:about="">')
        lines.append(
            f'    <ns0:hasPart xmlns:ns0="http://www.hancom.co.kr/hwpml/2016/meta/pkg#"'
            f' rdf:resource="Contents/{sec}"/>'
        )
        lines.append("  </rdf:Description>")
        lines.append(f'  <rdf:Description rdf:about="Contents/{sec}">')
        lines.append(
            '    <rdf:type rdf:resource="http://www.hancom.co.kr/hwpml/2016/meta/pkg#SectionFile"/>'
        )
        lines.append("  </rdf:Description>")

    # Document type declaration
    lines.append('  <rdf:Description rdf:about="">')
    lines.append(
        '    <rdf:type rdf:resource="http://www.hancom.co.kr/hwpml/2016/meta/pkg#Document"/>'
    )
    lines.append("  </rdf:Description>")

    lines.append("</rdf:RDF>")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Preview text extraction
# ---------------------------------------------------------------------------

def extract_preview_text(section_path: str, max_chars: int = 500) -> str:
    """Extract plain text from <hp:t>...</hp:t> tags in a section XML file.
    Returns the first ``max_chars`` characters."""
    try:
        with open(section_path, "r", encoding="utf-8") as f:
            xml_content = f.read()
    except (OSError, UnicodeDecodeError):
        return ""

    # Match <hp:t> ... </hp:t> including possible attributes
    texts = re.findall(r"<hp:t[^>]*>(.*?)</hp:t>", xml_content, re.DOTALL)
    joined = "\n".join(t.strip() for t in texts if t.strip())
    # Unescape basic XML entities
    joined = (
        joined.replace("&amp;", "&")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", '"')
        .replace("&apos;", "'")
    )
    return joined[:max_chars]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _xml_escape(text: str) -> str:
    """Escape text for safe inclusion in XML."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&apos;")
    )


def _make_id(filename: str) -> str:
    """Turn a filename like 'my-image.jpg' into a safe XML id like 'my_image'."""
    name = os.path.splitext(filename)[0]
    # Replace non-alphanumeric (excluding underscore) with underscore
    return re.sub(r"[^A-Za-z0-9_]", "_", name)


def _compression_for(entry_name: str) -> int:
    """Return the appropriate ZIP compression method for a given entry."""
    basename = os.path.basename(entry_name)
    ext = os.path.splitext(basename)[1].lower()

    if basename == "mimetype":
        return zipfile.ZIP_STORED
    if basename == "version.xml":
        return zipfile.ZIP_STORED
    if ext in IMAGE_EXTENSIONS:
        return zipfile.ZIP_STORED
    return zipfile.ZIP_DEFLATED


# ---------------------------------------------------------------------------
# ZIP assembly
# ---------------------------------------------------------------------------

def assemble_hwpx(work_dir: str, output_path: str) -> None:
    """Create the HWPX ZIP archive from the working directory.

    Entry order matters:
    1. mimetype (STORED, must be first)
    2. version.xml (STORED)
    3. META-INF/ files
    4. settings.xml
    5. Contents/ files (header, sections)
    6. BinData/ files (images)
    7. Preview/ files
    """
    # Collect all files in the work directory
    all_files: list[str] = []
    for root, _dirs, files in os.walk(work_dir):
        for fname in files:
            full = os.path.join(root, fname)
            rel = os.path.relpath(full, work_dir)
            all_files.append(rel)

    # Sort into the required order
    def _sort_key(entry: str) -> tuple:
        if entry == "mimetype":
            return (0, entry)
        if entry == "version.xml":
            return (1, entry)
        if entry.startswith("META-INF/"):
            return (2, entry)
        if entry == "settings.xml":
            return (3, entry)
        if entry.startswith("Contents/"):
            # header.xml first, then sections in order
            basename = os.path.basename(entry)
            if basename == "content.hpf":
                return (4, 0, entry)
            if basename == "header.xml":
                return (4, 1, entry)
            return (4, 2, entry)
        if entry.startswith("BinData/"):
            return (5, entry)
        if entry.startswith("Preview/"):
            return (6, entry)
        return (7, entry)

    ordered = sorted(all_files, key=_sort_key)

    output_abs = os.path.abspath(output_path)
    os.makedirs(os.path.dirname(output_abs) or ".", exist_ok=True)

    with zipfile.ZipFile(output_abs, "w") as zf:
        for entry in ordered:
            full_path = os.path.join(work_dir, entry)
            compression = _compression_for(entry)
            zf.write(full_path, entry, compress_type=compression)


# ---------------------------------------------------------------------------
# Main build logic
# ---------------------------------------------------------------------------

def build_hwpx(args: argparse.Namespace) -> str:
    """Orchestrate the full HWPX build. Returns the output file path."""

    template_dir = os.path.abspath(args.template)
    if not os.path.isdir(template_dir):
        print(f"[ERROR] Template directory not found: {template_dir}", file=sys.stderr)
        sys.exit(1)

    # Validate section files
    section_inputs: list[str] = []
    for s in args.section:
        s_abs = os.path.abspath(s)
        if not os.path.isfile(s_abs):
            print(f"[ERROR] Section file not found: {s_abs}", file=sys.stderr)
            sys.exit(1)
        section_inputs.append(s_abs)

    # Validate optional header
    header_override: str | None = None
    if args.header:
        header_override = os.path.abspath(args.header)
        if not os.path.isfile(header_override):
            print(f"[ERROR] Header file not found: {header_override}", file=sys.stderr)
            sys.exit(1)

    # Validate optional images
    image_inputs: list[str] = []
    if args.images:
        for img in args.images:
            img_abs = os.path.abspath(img)
            if not os.path.isfile(img_abs):
                print(f"[ERROR] Image file not found: {img_abs}", file=sys.stderr)
                sys.exit(1)
            ext = os.path.splitext(img_abs)[1].lower()
            if ext not in IMAGE_EXTENSIONS:
                print(
                    f"[WARNING] '{os.path.basename(img_abs)}' has extension '{ext}' "
                    f"which is not a recognized image type ({', '.join(sorted(IMAGE_EXTENSIONS))}). "
                    f"Including it anyway.",
                    file=sys.stderr,
                )
            image_inputs.append(img_abs)

    # Determine section filenames (section0.xml, section1.xml, ...)
    section_names: list[str] = []
    for i, _ in enumerate(section_inputs):
        section_names.append(f"section{i}.xml")

    image_names: list[str] = [os.path.basename(p) for p in image_inputs]

    title = args.title or ""
    date_str = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")

    # --- Work in a temporary directory ---
    tmp_dir = tempfile.mkdtemp(prefix="hwpx_build_")
    try:
        print(f"[INFO] Working directory: {tmp_dir}")

        # 1. Copy base template files
        print(f"[INFO] Copying base template from: {template_dir}")
        _copy_template(template_dir, tmp_dir)

        # 2. Place section files into Contents/, injecting secPr if missing
        contents_dir = os.path.join(tmp_dir, "Contents")
        os.makedirs(contents_dir, exist_ok=True)
        secpr_template_path = os.path.join(template_dir, "secpr_template.xml")
        for src, name in zip(section_inputs, section_names):
            dst = os.path.join(contents_dir, name)
            shutil.copy2(src, dst)
            # Auto-inject secPr if the section doesn't contain one
            with open(dst, "r", encoding="utf-8") as f:
                sec_content = f.read()
            if "<hp:secPr" not in sec_content and os.path.isfile(secpr_template_path):
                with open(secpr_template_path, "r", encoding="utf-8") as f:
                    secpr_xml = f.read().strip()
                # Insert secPr inside the first <hp:run> of the first <hp:p>
                # Pattern: after first <hp:run charPrIDRef="N">
                injected = re.sub(
                    r'(<hp:run charPrIDRef="\d+">)',
                    r'\1' + secpr_xml,
                    sec_content,
                    count=1,
                )
                if injected != sec_content:
                    with open(dst, "w", encoding="utf-8") as f:
                        f.write(injected)
                    print(f"[INFO] Section: {name} <- {src} (secPr auto-injected)")
                else:
                    print(f"[INFO] Section: {name} <- {src} (secPr injection failed, no matching run)")
            else:
                reason = "already has secPr" if "<hp:secPr" in sec_content else "no template"
                print(f"[INFO] Section: {name} <- {src} ({reason})")

        # 3. Optional header override
        if header_override:
            dst = os.path.join(contents_dir, "header.xml")
            shutil.copy2(header_override, dst)
            print(f"[INFO] Header override: {header_override}")

        # 4. Copy images to BinData/
        if image_inputs:
            bindata_dir = os.path.join(tmp_dir, "BinData")
            os.makedirs(bindata_dir, exist_ok=True)
            for src, name in zip(image_inputs, image_names):
                dst = os.path.join(bindata_dir, name)
                shutil.copy2(src, dst)
                print(f"[INFO] Image: BinData/{name} <- {src}")

        # 5. Generate container.rdf
        rdf_content = generate_container_rdf(section_names)
        rdf_path = os.path.join(tmp_dir, "META-INF", "container.rdf")
        os.makedirs(os.path.dirname(rdf_path), exist_ok=True)
        with open(rdf_path, "w", encoding="utf-8") as f:
            f.write(rdf_content)
        print(f"[INFO] Generated META-INF/container.rdf ({len(section_names)} section(s))")

        # 6. Generate content.hpf
        hpf_content = generate_content_hpf(
            template_dir, section_names, image_names, title, date_str
        )
        hpf_path = os.path.join(contents_dir, "content.hpf")
        with open(hpf_path, "w", encoding="utf-8") as f:
            f.write(hpf_content)
        print(f"[INFO] Generated Contents/content.hpf (title='{title}')")

        # 7. Generate Preview/PrvText.txt
        preview_dir = os.path.join(tmp_dir, "Preview")
        os.makedirs(preview_dir, exist_ok=True)
        # Extract text from the first section
        preview_text = extract_preview_text(
            os.path.join(contents_dir, section_names[0])
        )
        prv_path = os.path.join(preview_dir, "PrvText.txt")
        with open(prv_path, "w", encoding="utf-8") as f:
            f.write(preview_text)
        print(f"[INFO] Generated Preview/PrvText.txt ({len(preview_text)} chars)")

        # 8. Assemble the ZIP
        output_abs = os.path.abspath(args.output)
        assemble_hwpx(tmp_dir, output_abs)
        print(f"[INFO] HWPX assembled successfully.")

        # Verify the result
        size = os.path.getsize(output_abs)
        print(f"[INFO] Output: {output_abs} ({size:,} bytes)")

        # Quick sanity check: mimetype must be first entry
        with zipfile.ZipFile(output_abs, "r") as zf:
            first = zf.namelist()[0]
            if first != "mimetype":
                print(
                    f"[WARNING] First ZIP entry is '{first}', expected 'mimetype'. "
                    f"The file may not open correctly in Hancom Office.",
                    file=sys.stderr,
                )
            else:
                # Verify mimetype is stored uncompressed
                info = zf.getinfo("mimetype")
                if info.compress_type != zipfile.ZIP_STORED:
                    print(
                        "[WARNING] 'mimetype' entry is compressed. It should be STORED.",
                        file=sys.stderr,
                    )

            entry_count = len(zf.namelist())
            print(f"[INFO] ZIP contains {entry_count} entries: {', '.join(zf.namelist())}")

        return output_abs

    finally:
        # Clean up temp directory
        shutil.rmtree(tmp_dir, ignore_errors=True)


def _copy_template(src_dir: str, dst_dir: str) -> None:
    """Recursively copy template files into the work directory, preserving
    directory structure. Skips section*.xml files since those will be provided
    by the caller."""
    for root, dirs, files in os.walk(src_dir):
        rel_root = os.path.relpath(root, src_dir)
        dst_root = os.path.join(dst_dir, rel_root) if rel_root != "." else dst_dir

        for d in dirs:
            os.makedirs(os.path.join(dst_root, d), exist_ok=True)

        for fname in files:
            # Skip template section files -- we replace them with provided ones
            if re.match(r"^section\d+\.xml$", fname):
                continue
            src_file = os.path.join(root, fname)
            dst_file = os.path.join(dst_root, fname)
            shutil.copy2(src_file, dst_file)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Assemble a valid HWPX file from section XML and base template files.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""\
Examples:
  python3 build_hwpx.py --section section0.xml --output report.hwpx
  python3 build_hwpx.py --section s0.xml --section s1.xml --output multi.hwpx
  python3 build_hwpx.py --section s0.xml -o out.hwpx --title "보고서" --images logo.png chart.jpg
  python3 build_hwpx.py --section s0.xml -o out.hwpx --header custom_header.xml
""",
    )
    parser.add_argument(
        "--section",
        required=True,
        action="append",
        metavar="FILE",
        help="Section XML file(s). First file becomes section0.xml, etc. Can be specified multiple times.",
    )
    parser.add_argument(
        "--output", "-o",
        required=True,
        metavar="FILE",
        help="Output HWPX file path.",
    )
    parser.add_argument(
        "--template",
        default=DEFAULT_TEMPLATE,
        metavar="DIR",
        help=f"Path to base template directory (default: {DEFAULT_TEMPLATE}).",
    )
    parser.add_argument(
        "--header",
        default=None,
        metavar="FILE",
        help="Optional custom header.xml to replace the template default.",
    )
    parser.add_argument(
        "--title",
        default="",
        metavar="TEXT",
        help="Document title for content.hpf metadata.",
    )
    parser.add_argument(
        "--images",
        nargs="+",
        default=None,
        metavar="FILE",
        help="Optional image files to include in BinData/.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    output = build_hwpx(args)
    print(output)


if __name__ == "__main__":
    main()
